# Generated by Django 3.1.4 on 2021-12-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211231_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('date', models.TimeField()),
                ('segundos', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='informacion',
            name='date',
            field=models.TimeField(),
        ),
    ]
